config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  resources :candies do
    resources :order_items, only: [:create]
  end

  resources :order_items, only: [:destroy]

  resources :orders, only: [:show]  do
    collection  do
      get "my_orders"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candy.rb
class Candy < ApplicationRecord

include PgSearch::Model
pg_search_scope :search_by_name,
  against: [ :name ],
  using: {
    tsearch: { prefix: true }
  }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :order_items

  belongs_to :user
  has_many :order_items, dependent: :destroy
  validates :name, presence: true
  validates :composition, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :availability, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  def total_pay
    total = 0
    self.order_items.each do |item|
      next if item.quantity.nil?
      total += item.quantity * item.candy.price
    end
    return total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :candy
  belongs_to :order

  validates :quantity, presence: true
  validates :minutes, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy

  #enlever le panier si pas d'user

  has_many :candies, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :current_order
   before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def current_order
    if current_user.present?
      current_order = current_user.orders.last
      if current_order.present? && !current_order.payed
        @current_order = current_order
      end
    end
  end
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @candies = Candy.all
      if params[:query].present?
        sql_query = "name ILIKE :query"
         @candies = Candy.search_by_name params[:query]
        end


    @candies = @candies.geocoded
    @markers = @candies.map do |candy|
      {
        lat: candy.latitude,
        lng: candy.longitude,
        infoWindow: render_to_string(partial: "candies/infowindow", locals: { candy: candy })
      }
    end
  end

  def show
    @candy = Candy.find(params[:id])
    @order_item = OrderItem.new
  end

  def new
    @candy = Candy.new
  end

  def create
    @candy = Candy.new(candy_params)
    @candy.user = current_user
    if @candy.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
    @candy = current_user.candies.find_by(id: params[:id])
  end

  def update
    @candy = Candy.find(params[:id])
    if @candy.update(candy_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def destroy
    @candy = Candy.find(params[:id])
    @candy.destroy
    redirect_to candies_path
  end


  private

  def candy_params
    params.require(:candy).permit(:name, :composition, :address, :price, :availability)
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def index
    @order_items = OrderItem.all
  end

  def show
    @order_item = OrderItem.find(params[:id])
  end

  def new
    @order_item = OrderItem.new
  end

  def create
    #creer un panier si payed true
    @order = current_order
    if @order.nil?
      @order = Order.create(user: current_user)
    end
    @order_item = OrderItem.new(order_items_params)
    @candy = Candy.find(params[:candy_id])
    @order_item.candy = @candy
    @order_item.order = @order
    if @order_item.save
      redirect_to @candy
    else
      render :new
    end
  end

  def edit
    @order_item = OrderItem.find(params[:id])
  end

  def update
     if @order_item.update(order_items_params)
      redirect_to order_items_path
    else
      render :edit
    end
  end

  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy
    redirect_to my_orders_orders_path
  end


  private

  def order_items_params
    params.require(:order_item).permit(:quantity, :minutes)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def add
    @order = Order.create(user: current_user)
      @order_item = Order_item.find(params[:id])
      @order_item.order = @order
  end

  def my_orders
   @my_orders = current_user.orders.where(payed: false)
   @total_orders = @my_orders.map(&:total_pay).sum
  end

  def show
    @orders = Orders.find(params[:id])
  end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @candies = Candy.all
  end

  def profile
    @orders = current_user.orders
    @username = current_user.username
    @candies = current_user.candies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candies/_form.html.erb
<div class="candyform">
<%= simple_form_for(@candy) do |f| %>
  <%= f.input :name %>
  <%= f.input :composition %>
  <%= f.input :address%>
  <%= f.input :price, input_html: { min: '1', step: 'any' } %>
  <%= f.input :availability, input_html: { min: '1', step: 'any' } %>

<%= f.submit class: 'btn btn-primary' %>
<% end %>
</div>

app/views/candies/_infowindow.html.erb
<h2><%= candy.name %></h2>
<p><%= candy.address %></p>

app/views/candies/edit.html.erb
<h1>Edit <%= @candy.name %></h1>

<%= render "form" %>

<%= link_to "Back", profile_path , class:'btn btn-primary'%>

app/views/candies/index.html.erb
<!-- candy product -->

<div class="center-box1 candies-container">

    <div class="cards">
      <% @candies.each do |candy|%>
        <div class="candybox">
          <h2><%= candy.name %></h2>
          <%= link_to "View details", candy_path(candy), class:"btn btn-flat" %>
        </div>
      <% end %>
    </div>



  <div id="map"
    style="width: 100%;
    width: 600px;

    height: 1000px;"


    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
</div>

app/views/candies/new.html.erb
<div>
<h1>Add a new candy</h1>
</div>


<%= render 'form', candy: @candy %>

<%= link_to "Back", root_path, class:'btn btn-primary'%>

app/views/candies/show.html.erb
<div class="container">
  <div class="box">
    <img src="https://cdn.hellosubscription.com/wp-content/uploads/2018/12/28012446/korean-snack-box-january-2019-6.jpg" />
    <div class="card-trip-infos">
      <div>
        <h2><strong> <%= @candy.name %></strong></h2>
        <p><%= @candy.composition %></p>
        <p><span> <%= @candy.address %></span></p>
        <p><span> Available boxes: <%= @candy.availability %></span></p>
      </div>
      <h2 class="card-trip-pricing"><%= @candy.price%> $</h2>
    </div>
  </div>

  <%= simple_form_for [@candy, @order_item] do |f| %>
    <div class="qty">
      <%= f.input :quantity, placeholder: '1', input_html: { value: '1', min: '1', max: @candy.availability, step: 'any' } %>
      <%= f.input :minutes, placeholder: "Minimum pick-up time is 15 min. Maximum is 60 min", input_html: { value: '15', min: 15, max: 60 } %>
    </div>
    <div class="pick-up-time"></div>
    <%= f.submit "Add to card", class: 'btn-primary' %>
  <% end %>
</div>


<%= link_to "Back", candies_path , class:'btn btn-primary'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/layouts/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Anyo<strong>candies</strong> to <strong>creative people</strong>!</h1>
    <p>Eat candies</p>
    <a class="btn btn-flat" href="#">Buy now</a>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

app/views/orders/my_orders.html.erb
<div class="wrap">
  <div class="wrap2">

<% @my_orders.each do |order|%>
  <% order.order_items.each do |item| %>
<div class="card-product">
  <img src="https://cdn.hellosubscription.com/wp-content/uploads/2018/12/28012446/korean-snack-box-january-2019-6.jpg" />
  <div class="card-product-infos">
              <p><strong><%= item.candy.name%></strong> - <%= item.candy.composition%>
              <span><p>Price : <%= item.candy.price %>  $</p></span>
              <span><p>Total quantity : <%= item.quantity %> </p></span>
              <span><p>Pick-up time : <%= (item.created_at + (item.minutes || 0).minutes).strftime("%H:%M") %></p></span>
              <%= link_to "❌", order_item_path(item),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %></p>
  </div>
</div>
          <% end %>
    <% end %>
</div>






<div class="boxx">
  <% @my_orders.each do |order|%>
    <% order.order_items.each do |item| %>
      <ul>
        <%= item.candy.name %> - <%= item.quantity %> box(es)
      </ul>
      <% end %>
  <% end %>
  Total to pay: <%= @total_orders %> $
  <%= link_to "Checkout", root_path, class:'btn btn-primary'%>
</div>
</div>


  <%= link_to "Back", candies_path, class:'btn btn-primary'%>

app/views/pages/home.html.erb
<div class="container">
  <div class="first-card">
    <div class="logo-search">
     <div class="logo">
      ANYO
      </div>
    </div>
      <div class="home-text">
        <h2>Anyo is your one stop shop for connections to Korean confections! Browse, make a selection, and have your items in minutes.</h2>
      </div>
  </div>
</div>

<div class="container">
  <div class="topnav">
    <form action="candies" method="get">
    <%= text_field_tag :query, params[:query], placeholder:"Enter your favorite candy" %>
  </div>
  <span>
    <button <%= link_to "Search", candies_path, id:"roger", class:"search-button" %>
    </button>
  </span>
  </form>
  <div class="topnav">
    <%= link_to "Sell your candies", new_candy_path, class:"btn btn-primary" %>
  </div>
</div>


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
    Thanks for visiting!
  </div>
</div>

app/views/pages/index.html.erb
<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>



  <div class="body">
   -->

app/views/pages/profile.html.erb
<div class="logo2">
      ANYO
      </div>
<div class="topname">
  Hello <%= @username %>
</div>


<div class="profile-box">

    <ul>
        <% @orders.each do |order|%>
          <p>You have the following items in your basket:</p>
          <%  order.order_items.each do |order_item|%>
         <%= order_item.candy.name %> <%= link_to '🟢', my_orders_orders_path, title:"Confirm" %>
          <%end%>
    <%end%>
     </ul>

    <% if !@candies.last.nil? %>

      <div class="box2">You have the following items on sale:
        <ul>
          <%= @candies&.last&.name %> - <%= @candies&.last&.availability %> box(es)
                  <%= link_to "🔴", candy_path(@candies&.last), title:"Delete",
                            method: :delete,
                            data: { confirm: "Are you sure?" } %>
          <%= link_to "🟠", edit_candy_path(@candies&.last), title:"Edit" %>
        </div>
      <% end %>
    </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" >
  <%= link_to "#", class: "navbar-brand" do %>
  <div class="wrapper">
    <% if @current_order.present? %>
    <%= link_to '🛒', my_orders_orders_path, class:"fa" %>
    <%= @current_order.order_items.count %>
  <% end %>
  <% end %>
</div>

<div class="collapse navbar-collapse dropdown" id="navbarSupportedContent">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </button>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active dropdown-menu">
        <%= link_to "Home", root_path, class: "nav-link" %>
        <%= link_to "Login", user_session_path, class: "nav-link" %>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <%= link_to "Profile page", profile_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>